### ISSUE TITLE
Question regarding setdiff(1:8, state)

### ISSUE THREAD

**Issue by skjerns** [YunzheLiu/TDLM#1]
Dear Yungzhe Liu,

Thanks again for publishing this package, it's very useful! I'm currently going through the code and trying to understand it in detail.

When going through the code I was wondering about the part `setdiff(1:8, state)` 
https://github.com/YunzheLiu/TDLM/blob/a4f878130525ba8b73e101c55dc562fe29f164a0/Simulate_Replay.m#L93
If I understand correctly we want to take the inverse set of `state` (e.g. `0,0,1,0,0,0,0,0`), i.e. `~state` (e.g. `1,1,0,1,1,1,1,1`), is that correct? However, as `state` is a binary array, `setdiff(1:8, state)`  will always result in `2,3,4,5,6,7,8` and not e.g. `1,2,4,5,6,7,8`. Am I understanding that part correctly? Feel free to correct me if I'm wrong or misunderstood what is happening in this line.

Best regards,
Simon Kern

**Comment by YunzheLiu** [comment]
this line of code will be adding both the specific state reactivation e.g., state1, and the average of all others. It was intended to test sth else. For your purpose, I think you can just get rid of the nanmean part, I will also update the code soon.

**Comment by skjerns** [comment]
Thank's alot for your quick response!

May I ask what kind of update you are planning to do? Just a restructuring of the code, or also major changes? 

As mentioned via mail we're currently working with the code base and trying to replicate the methods using a slightly adapted paradigm. To validate if our setup of the code is wrong it would be very useful to have some validation data set. Do you think it would be possible to gain access to the data used in this project, and if so, what would be the best way to proceed? 

Thank you again alot for your amazing work!

**Comment by YunzheLiu** [comment]
There is no major change, but perhaps, more extensions. Sorry for missing your previous email. Please write to me again.
